<a href="https://colab.research.google.com/github/wendoughlee/PyTorch/blob/main/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [5]:
import torch

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [6]:
# Scalar
# no dimensions, just a number
# lowercase variable name

scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [9]:
# Get tensor back as int
scalar.item()

7

In [10]:
# Vector
# Typically has more than one number
# lowercase variable name

vector = torch.tensor([7, 7,])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
# Shape
# Shape of vector, elements per row? 1x2?
vector.shape

torch.Size([2])

In [15]:
# MATRIX
# 2 dimensional
# uppercase variable name

MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
# MATRIX dimensions
MATRIX.ndim

2

In [17]:
# MATRIX shape
# Elements, it is a 2x2 so a total of 4 elements
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
# any number of dimensions, most likely 3?
# uppercase variable name

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
# TENSOR dimensions
TENSOR.ndim

3

In [23]:
# TENSOR shape,
TENSOR.shape

# 1 matches with outermost bracket
# 3 matches with middle bracket
# 3 matches with innermost brackets

torch.Size([1, 3, 3])

TENSOR shape guide: [guide](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png
)

In [24]:
# TENSOR example
TENSOR2 = torch.tensor([[[[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]]])
TENSOR2


tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]]])

In [25]:
TENSOR2.ndim

4

In [26]:
TENSOR2.shape

torch.Size([1, 1, 4, 4])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers, and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random nunbers -> look at data -> update random numbers`

Torch random tensors : [torch random sensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [27]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7539, 0.3965, 0.4914, 0.3653],
        [0.7815, 0.7340, 0.2193, 0.5950],
        [0.3652, 0.5227, 0.8633, 0.1290]])

In [28]:
random_tensor.ndim

2

In [31]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
# Used for masking
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
# .dtype , default data type
# default data type for tensors are floats
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [42]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1) # start: starting number, end: final number, step: incrementation
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) # creating tensor full of zeros in the same shape as one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on right device

In [48]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is tensor (float32, float16)
                                                device=None, # what device is tensor on
                                                requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [49]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [50]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Stopped at 2:02:56